<?php

use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */

function jsonapi_explorer_form_jsonapi_settings_alter(&$form) {
  if (\Drupal::currentUser()->hasPermission('use the jsonapi explorer')) {
    global $base_url;
    \Drupal::messenger()->addStatus(t('Explore your API by <a href=":href" target="_blank">visiting the explorer!</a>', [
      ':href' => Url::fromRoute('jsonapi_explorer.app.index', [], [
        'query' => [
          'location' => $base_url,
        ],
      ])->toString(),
    ]));
  }
}
